# Generated by Django 2.2 on 2019-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
