# Generated by Django 2.2 on 2019-09-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_productionline_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
