# Generated by Django 2.2 on 2019-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20190928_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
