# Generated by Django 2.2 on 2019-09-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('main', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ManyToManyField(blank=True, default=None, related_name='_message_answers_+', to='user_messages.Message')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
