# Generated by Django 2.2 on 2019-09-25 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=220)),
                ('profile_picture', models.ImageField(blank=True, default='uploads/profile/profile.png', upload_to=profiles.models.get_file_path, validators=[profiles.validators.validate_ext])),
                ('website', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
