# Generated by Django 2.2 on 2019-09-25 22:30

from django.db import migrations, models
import posts.models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190925_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_upload_path, validators=[posts.validators.validate_ext]),
        ),
    ]
